version: '2'

services:
  postgres:
    image: 'postgres:11.5'
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    env_file:
      - '.env'

  userlogin_app:
    build: .
    #command: gunicorn -b 0.0.0.0:8001 --access-logfile - --reload "userlogin.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/userlogin'
    ports:
      - '8001:8001'
    depends_on:
      - "postgres"

volumes:
  postgres: {}
