version: '2'

services:
  postgres:
    image: 'postgres:11.5'
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    env_file:
      - '.env'

  redis:
    image: 'redis:6.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  userlogin_app:
    build: .
    #command: gunicorn -b 0.0.0.0:8001 --access-logfile - --reload "userlogin.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/userlogin'
    ports:
      - '8001:8001'
    depends_on:
      - "postgres"

  celery:
    build: .
    command: celery worker -B -l debug -A userlogin.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/userlogin'
    depends_on:
      - "userlogin_app"
      - "redis"


volumes:
  postgres: {}
  redis: {}
